drop table if exists genre, films, place;

CREATE TABLE genre
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256)
);

CREATE TABLE FILMS
(
    ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(256),
    GENRE_ID BIGINT REFERENCES genre(ID)
);

CREATE TABLE place
(
    ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME    VARCHAR(256),
    FILM_ID BIGINT REFERENCES FILMS(ID)
);

